# Generated by Django 4.0.4 on 2024-06-10 17:44

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_alter_order_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airplane_image_file_path),
        ),
    ]
